// src/examples/chapter-15/client/angular/src/app/quest/quest.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Observable, Subscription } from 'rxjs';
import { GameStateService, GenerateRecipeService, CreateImageService, EvaluateDishService } from '../services';
import { GameState, GameStep } from '../../domain/models/game';

@Component({
  selector: 'app-quest',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './quest.component.html',
  styleUrl: './quest.component.css'
})
export class QuestComponent implements OnInit, OnDestroy {
  state$: Observable<GameState>;
  availableIngredients: Array<{name: string, emoji: string}> = [];
  GameStep = GameStep; // Expose enum to template
  
  private subscriptions = new Subscription();

  constructor(
    private gameStateService: GameStateService,
    private generateRecipeService: GenerateRecipeService,
    private createImageService: CreateImageService,
    private evaluateDishService: EvaluateDishService
  ) {
    this.state$ = this.gameStateService.state$;
    this.availableIngredients = this.gameStateService.availableIngredients;
  }

  ngOnInit(): void {
    // Subscribe to recipe stream
    this.subscriptions.add(
      this.generateRecipeService.recipeStream$.subscribe(response => {
        if (response.type === 'content' && response.content) {
          const currentState = this.gameStateService.currentState;
          const newRecipe = (currentState.recipe || '') + response.content;
          this.gameStateService.setRecipe(newRecipe);
        } else if (response.type === 'done') {
          // Recipe generation complete, wait before moving to image step
          setTimeout(() => {
            this.gameStateService.startImageGeneration();
            this.createDishImage();
          }, 1500);
        } else if (response.type === 'error') {
          this.gameStateService.setError(response.error || 'Recipe generation failed');
        }
      })
    );
  }

  ngOnDestroy(): void {
    this.subscriptions.unsubscribe();
  }

  startGame(): void {
    this.gameStateService.startGame();
  }

  toggleIngredient(ingredient: string): void {
    const state = this.gameStateService.currentState;
    if (state.selectedIngredients.includes(ingredient)) {
      this.gameStateService.removeIngredient(ingredient);
    } else {
      this.gameStateService.addIngredient(ingredient);
    }
  }

  async startRecipeGeneration(): Promise<void> {
    const state = this.gameStateService.currentState;
    if (state.selectedIngredients.length === 4) {
      this.gameStateService.startRecipeGeneration();
      await this.generateRecipeService.generateRecipe({
        ingredients: state.selectedIngredients
      });
    }
  }

  private async createDishImage(): Promise<void> {
    const state = this.gameStateService.currentState;
    if (state.recipe) {
      const dishName = this.extractDishName(state.recipe);
      
      // Simulate progress while generating
      let currentProgress = 0;
      const progressInterval = setInterval(() => {
        currentProgress += 15;
        if (currentProgress <= 90) {
          this.gameStateService.setImageProgress(currentProgress);
        }
      }, 300);
      
      try {
        const result = await this.createImageService.createImage({
          dishName,
          description: `A beautiful dish made with: ${state.selectedIngredients.join(', ')}`
        });
        
        clearInterval(progressInterval);
        
        if (result && result.success && result.imageUrl) {
          this.gameStateService.setImage(result.imageUrl);
          // Wait before moving to evaluation step
          setTimeout(() => {
            this.gameStateService.startEvaluation();
            setTimeout(() => {
              this.evaluateDishStep();
            }, 1000);
          }, 1000);
        } else {
          this.gameStateService.setError('Image generation failed');
        }
      } catch (error) {
        clearInterval(progressInterval);
        this.gameStateService.setError('Image generation failed');
      }
    }
  }

  private async evaluateDishStep(): Promise<void> {
    const state = this.gameStateService.currentState;
    if (state.recipe) {
      const dishName = this.extractDishName(state.recipe);
      const result = await this.evaluateDishService.evaluateDish({
        dishName,
        description: state.recipe
      });
      
      if (result && result.success) {
        this.gameStateService.setEvaluation({
          score: result.score || 0,
          feedback: result.feedback || '',
          title: result.title,
          achievement: result.achievement
        });
      } else {
        this.gameStateService.setError('Evaluation failed');
      }
    }
  }

  private extractDishName(recipe: string): string {
    // Simple extraction - look for title patterns or use ingredients
    const lines = recipe.split('\n');
    const titleLine = lines.find(line => 
      line.includes('#') || 
      line.toLowerCase().includes('recipe') ||
      line.toLowerCase().includes('dish')
    );
    
    if (titleLine) {
      return titleLine.replace(/#+\s*/, '').trim();
    }
    
    // Fallback to ingredient combination
    const state = this.gameStateService.currentState;
    return state.selectedIngredients.join(' ') + ' dish';
  }

  resetGame(): void {
    this.gameStateService.resetGame();
  }

  getStepIndex(step: GameStep): number {
    const stepOrder = [GameStep.Ready, GameStep.SelectIngredients, GameStep.Recipe, GameStep.Image, GameStep.Evaluation, GameStep.Result];
    return stepOrder.indexOf(step);
  }

  Math = Math; // Expose Math to template
}

<div class="quest-container" *ngIf="state$ | async as state">
  <!-- Fixed Progress Bar (only visible during processing) -->
  <div *ngIf="state.currentStep !== GameStep.Ready && state.currentStep !== GameStep.SelectIngredients && state.currentStep !== GameStep.Result" 
       class="fixed top-0 left-0 right-0 bg-white bg-opacity-95 backdrop-blur-md shadow-lg z-50 border-b-4 border-orange-300">
    <div class="max-w-5xl mx-auto px-4 py-4">
      <!-- Main Progress Bar -->
      <div class="mb-3">
        <div class="flex justify-between items-center mb-2">
          <div class="flex items-center gap-3">
            <div class="text-3xl animate-pulse">
              <span *ngIf="state.currentStep === GameStep.Recipe">🍳</span>
              <span *ngIf="state.currentStep === GameStep.Image">📸</span>
              <span *ngIf="state.currentStep === GameStep.Evaluation">⚖️</span>
            </div>
            <div>
              <div class="font-bold text-lg text-gray-800">
                <span *ngIf="state.currentStep === GameStep.Recipe">Creating Recipe</span>
                <span *ngIf="state.currentStep === GameStep.Image">Generating Image</span>
                <span *ngIf="state.currentStep === GameStep.Evaluation">Evaluating Dish</span>
              </div>
              <div class="text-sm text-gray-600">
                <span *ngFor="let ingredient of state.selectedIngredients; let i = index">
                  <span *ngFor="let availableIng of availableIngredients">
                    <span *ngIf="availableIng.name === ingredient">{{ availableIng.emoji }}</span>
                  </span>{{ i < state.selectedIngredients.length - 1 ? ' ' : '' }}
                </span>
                • {{ state.selectedIngredients.join(', ') }}
              </div>
            </div>
          </div>
          <div class="flex items-center gap-4">
            <div *ngIf="state.isLoading" class="flex items-center gap-2">
              <div class="w-6 h-6 border-2 border-orange-400 border-t-transparent rounded-full animate-spin"></div>
              <span class="text-sm text-gray-600">Processing...</span>
            </div>
            <div class="text-right">
              <div class="font-bold text-xl text-orange-600">{{ Math.round(state.progress) }}%</div>
            </div>
          </div>
        </div>
        <div class="w-full bg-gray-200 rounded-full h-3 overflow-hidden">
          <div class="h-full rounded-full transition-all duration-700 ease-out bg-gradient-to-r from-orange-400 to-red-500"
               [style.width.%]="state.progress">
          </div>
        </div>
      </div>
      
      <!-- Step Indicators -->
      <div class="flex justify-center items-center gap-2">
        <div *ngFor="let step of [GameStep.Recipe, GameStep.Image, GameStep.Evaluation, GameStep.Result]; let i = index" class="flex items-center">
          <div class="w-3 h-3 rounded-full border-2 transition-all duration-300"
               [class]="step === state.currentStep ? 'bg-orange-500 border-orange-500 scale-150 animate-pulse' : 
                       getStepIndex(state.currentStep) > getStepIndex(step) ? 'bg-green-500 border-green-500' : 
                       'bg-gray-300 border-gray-400'">
          </div>
          <div *ngIf="i < 3" class="w-12 h-px mx-1 transition-colors duration-300"
               [class]="getStepIndex(state.currentStep) > getStepIndex(step) ? 'bg-green-500' : 'bg-gray-300'">
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Main Content with Padding for Fixed Bar -->
  <div [class]="'transition-all duration-300 ' + 
    (state.currentStep !== GameStep.Ready && state.currentStep !== GameStep.SelectIngredients && state.currentStep !== GameStep.Result ? 'pt-32' : '')">
    
  <!-- Ready State -->
  <div *ngIf="state.currentStep === GameStep.Ready" class="text-center py-16">
    <div class="text-6xl mb-4">🎯</div>
    <h1 class="text-4xl font-bold mb-4 text-gray-800">Recipe Quest</h1>
    <p class="text-xl text-gray-600 mb-8">Challenge yourself to create amazing dishes!</p>
    <button 
      (click)="startGame()" 
      class="bg-orange-500 hover:bg-orange-600 text-white px-16 py-6 rounded-lg text-xl font-semibold transition-colors shadow-lg hover:shadow-xl">
      Start Quest
    </button>
  </div>

  <!-- Select Ingredients State -->
  <div *ngIf="state.currentStep === GameStep.SelectIngredients" class="max-w-4xl mx-auto">
    <div class="text-center mb-8">
      <div class="text-5xl mb-4">🎲</div>
      <h2 class="text-3xl font-bold mb-2 text-gray-800">Choose Your Ingredients</h2>
      <p class="text-lg text-gray-600 mb-4">Select exactly 4 ingredients for your recipe quest</p>
      <p class="text-sm text-gray-500">Selected: {{ state.selectedIngredients.length }}/4</p>
    </div>

    <!-- Ingredient Grid -->
    <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4 mb-8">
      <button 
        *ngFor="let ingredient of availableIngredients" 
        (click)="toggleIngredient(ingredient.name)"
        [class]="'p-5 rounded-lg border-2 text-center transition-all ' + 
          (state.selectedIngredients.includes(ingredient.name) 
            ? 'border-orange-400 bg-orange-50 shadow-md transform scale-105' 
            : 'border-gray-200 hover:border-orange-300 hover:bg-orange-50')"
        [disabled]="state.selectedIngredients.length >= 4 && !state.selectedIngredients.includes(ingredient.name)">
        <div class="text-2xl mb-2">{{ ingredient.emoji }}</div>
        <div class="text-sm font-medium capitalize">{{ ingredient.name }}</div>
      </button>
    </div>

    <!-- Generate Recipe Button -->
    <div class="text-center">
      <button 
        (click)="startRecipeGeneration()"
        [disabled]="state.selectedIngredients.length !== 4"
        [class]="'px-16 py-6 rounded-lg text-xl font-semibold transition-colors shadow-lg ' +
          (state.selectedIngredients.length === 4 
            ? 'bg-green-500 hover:bg-green-600 text-white hover:shadow-xl' 
            : 'bg-gray-300 text-gray-500 cursor-not-allowed')">
        Create Recipe ({{ state.selectedIngredients.length }}/4)
      </button>
    </div>
  </div>

  <!-- Recipe Generation State -->
  <div *ngIf="state.currentStep === GameStep.Recipe" class="max-w-4xl mx-auto">
    <div class="text-center mb-8">
      <div class="text-5xl mb-4 animate-pulse">🍳</div>
      <h2 class="text-3xl font-bold mb-2 text-gray-800">Creating Your Recipe</h2>
      <p class="text-lg text-gray-600">AI chef is working on your custom recipe...</p>
    </div>

    <div class="bg-white rounded-lg shadow-lg p-6">
      <div class="mb-4">
        <strong>Ingredients:</strong> {{ state.selectedIngredients.join(', ') }}
      </div>
      
      <div class="recipe-content bg-gray-50 p-4 rounded-lg min-h-[200px]">
        <div *ngIf="state.recipe" class="whitespace-pre-line">{{ state.recipe }}</div>
        <div *ngIf="!state.recipe && state.isLoading" class="text-gray-500">
          Generating recipe...
        </div>
      </div>
    </div>
  </div>

  <!-- Image Generation State -->
  <div *ngIf="state.currentStep === GameStep.Image" class="max-w-4xl mx-auto">
    <div class="text-center mb-8">
      <div class="text-5xl mb-4 animate-pulse">📸</div>
      <h2 class="text-3xl font-bold mb-2 text-gray-800">Creating Dish Image</h2>
      <p class="text-lg text-gray-600">Visualizing your delicious creation...</p>
    </div>

    <div class="bg-white rounded-lg shadow-lg p-6">
      <div *ngIf="state.imageUrl" class="text-center">
        <img [src]="state.imageUrl" alt="Generated dish image" class="w-full max-w-md h-auto rounded-lg mx-auto object-cover" />
      </div>
      <div *ngIf="!state.imageUrl && state.isGeneratingImage" class="text-center">
        <div class="mb-4">
          <div class="w-16 h-16 border-4 border-orange-400 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p class="text-gray-600 mb-2">Creating your dish visualization...</p>
          <div *ngIf="state.imageGenerationProgress !== undefined" class="text-sm text-gray-500">
            {{ Math.round(state.imageGenerationProgress) }}% complete
          </div>
        </div>
        
        <!-- Image Generation Progress Bar -->
        <div *ngIf="state.imageGenerationProgress !== undefined" class="w-full bg-gray-200 rounded-full h-2 mx-auto max-w-xs">
          <div class="h-full rounded-full bg-gradient-to-r from-blue-400 to-purple-500 transition-all duration-300"
               [style.width.%]="state.imageGenerationProgress">
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Evaluation State -->
  <div *ngIf="state.currentStep === GameStep.Evaluation" class="max-w-4xl mx-auto">
    <div class="text-center mb-8">
      <div class="text-5xl mb-4 animate-pulse">⚖️</div>
      <h2 class="text-3xl font-bold mb-2 text-gray-800">AI Judge Evaluation</h2>
      <p class="text-lg text-gray-600">Professional chef AI is rating your dish...</p>
    </div>

    <div class="bg-white rounded-lg shadow-lg p-6">
      <div class="text-center mb-6">
        <div class="animate-spin w-12 h-12 border-4 border-purple-400 border-t-transparent rounded-full mx-auto mb-4"></div>
        <p class="text-gray-600">Analyzing flavors, presentation, and creativity...</p>
      </div>
      
      <!-- Show the dish being evaluated -->
      <div class="grid md:grid-cols-2 gap-6 mb-6">
        <div *ngIf="state.recipe" class="bg-gray-50 p-4 rounded-lg">
          <h3 class="font-bold mb-2">Your Recipe</h3>
          <div class="text-sm text-gray-700 max-h-32 overflow-y-auto">{{ state.recipe }}</div>
        </div>
        <div *ngIf="state.imageUrl" class="text-center">
          <h3 class="font-bold mb-2">Your Creation</h3>
          <img [src]="state.imageUrl" alt="Your dish" class="w-full max-w-32 h-auto rounded-lg mx-auto object-cover" />
        </div>
      </div>
    </div>
  </div>

  <!-- Result State -->
  <div *ngIf="state.currentStep === GameStep.Result" class="max-w-4xl mx-auto">
    <div class="text-center mb-8">
      <div class="text-6xl mb-4">🏆</div>
      <h2 class="text-3xl font-bold mb-2 text-gray-800">Quest Complete!</h2>
      <div *ngIf="state.title" class="text-xl font-semibold text-orange-600 mb-2">{{ state.title }}</div>
      <div *ngIf="state.achievement" class="text-lg text-purple-600 mb-4">🎖️ {{ state.achievement }}</div>
    </div>

    <div class="bg-white rounded-lg shadow-lg p-6 mb-8">
      <!-- Recipe -->
      <div class="mb-6">
        <h3 class="text-xl font-bold mb-2">Your Recipe</h3>
        <div class="bg-gray-50 p-4 rounded-lg whitespace-pre-line">{{ state.recipe }}</div>
      </div>

      <!-- Image -->
      <div *ngIf="state.imageUrl" class="mb-6 text-center">
        <h3 class="text-xl font-bold mb-2">Your Creation</h3>
        <div class="flex justify-center">
          <img [src]="state.imageUrl" alt="Final dish" class="w-full max-w-sm h-auto rounded-lg object-cover shadow-md" />
        </div>
      </div>

      <!-- Score & Feedback -->
      <div class="text-center">
        <div *ngIf="state.score !== undefined" class="mb-4">
          <div class="text-4xl font-bold text-orange-600">{{ state.score }}/100</div>
          <div class="text-lg text-gray-600">Your Score</div>
        </div>
        
        <div *ngIf="state.feedback" class="bg-blue-50 p-4 rounded-lg">
          <h4 class="font-semibold mb-2">Chef's Feedback:</h4>
          <p class="text-gray-700">{{ state.feedback }}</p>
        </div>
      </div>
    </div>

    <div class="text-center">
      <button 
        (click)="resetGame()"
        class="bg-orange-500 hover:bg-orange-600 text-white px-16 py-6 rounded-lg text-xl font-semibold transition-colors shadow-lg hover:shadow-xl">
        Play Again
      </button>
    </div>
  </div>

  <!-- Error Display -->
  <div *ngIf="state.error" class="max-w-4xl mx-auto mt-8">
    <div class="bg-red-50 border border-red-200 rounded-lg p-4">
      <div class="flex items-center">
        <div class="text-red-500 text-xl mr-3">❌</div>
        <div>
          <h3 class="font-semibold text-red-800">Error</h3>
          <p class="text-red-700">{{ state.error }}</p>
        </div>
      </div>
      <div class="mt-4">
        <button 
          (click)="resetGame()"
          class="bg-red-500 hover:bg-red-600 text-white px-8 py-3 rounded-lg transition-colors shadow-md hover:shadow-lg">
          Reset Game
        </button>
      </div>
    </div>
  </div>
  
  </div> <!-- Close main content padding div -->
</div>

// src/examples/chapter-15/client/next/app/quest/page.tsx
'use client';

import { 
  GameProgress,
  GameResult,
  RecipeDisplay,
  ImageDisplay
} from '../../src/components';
import { useRecipeQuestGame } from '../hooks/use-recipe-quest-game';
import { GameStep } from '../../src/domain/models/game';

export default function RecipeQuestPage() {
  const { state, availableIngredients, actions } = useRecipeQuestGame();

  // Step info for fixed progress bar
  const stepInfo = {
    [GameStep.Ready]: { emoji: '🎯', title: 'Ready to Start' },
    [GameStep.SelectIngredients]: { emoji: '🎲', title: 'Choose Ingredients' },
    [GameStep.Recipe]: { emoji: '🍳', title: 'Creating Recipe' },
    [GameStep.Image]: { emoji: '📸', title: 'Generating Image' },
    [GameStep.Evaluation]: { emoji: '⚖️', title: 'Evaluating Dish' },
    [GameStep.Result]: { emoji: '🏆', title: 'Quest Complete' },
  }[state.currentStep] || { emoji: '🎯', title: 'Recipe Quest' };

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 to-red-50">
      {/* Fixed Progress Bar (only visible during processing) */}
      {(state.currentStep !== GameStep.Ready && state.currentStep !== GameStep.SelectIngredients && state.currentStep !== GameStep.Result) && (
        <div className="fixed top-0 left-0 right-0 bg-white/98 backdrop-blur-md shadow-lg z-50 border-b-4 border-orange-300">
          <div className="max-w-5xl mx-auto px-4 py-4">
            {/* Main Progress Bar */}
            <div className="mb-3">
              <div className="flex justify-between items-center mb-2">
                <div className="flex items-center gap-3">
                  <div className="text-3xl animate-pulse">{stepInfo.emoji}</div>
                  <div>
                    <div className="font-bold text-lg text-gray-800">{stepInfo.title}</div>
                    <div className="text-sm text-gray-600">
                      {state.selectedIngredients.map(ing => {
                        const data = availableIngredients.find(a => a.name === ing);
                        return data?.emoji;
                      }).join(' ')} • {state.selectedIngredients.join(', ')}
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  {state.isLoading && (
                    <div className="flex items-center gap-2">
                      <div className="w-6 h-6 border-2 border-orange-400 border-t-transparent rounded-full animate-spin" />
                      <span className="text-sm text-gray-600">Processing...</span>
                    </div>
                  )}
                  <div className="text-right">
                    <div className="font-bold text-xl text-orange-600">{Math.round(state.progress)}%</div>
                  </div>
                </div>
              </div>
              <div className="w-full bg-gray-200 rounded-full h-3 overflow-hidden">
                <div
                  className={`
                    h-full rounded-full transition-all duration-700 ease-out
                    ${state.isLoading 
                      ? 'bg-gradient-to-r from-orange-400 via-red-500 to-orange-400 animate-gradient'
                      : 'bg-gradient-to-r from-orange-400 to-red-500'
                    }
                  `}
                  style={{ width: `${state.progress}%` }}
                />
              </div>
            </div>
            
            {/* Step Indicators */}
            <div className="flex justify-center items-center gap-2">
              {Object.values(GameStep).filter(step => 
                step !== GameStep.Ready && step !== GameStep.SelectIngredients
              ).map((step, index) => {
                const isActive = step === state.currentStep;
                const isCompleted = Object.values(GameStep).indexOf(state.currentStep) > Object.values(GameStep).indexOf(step);
                
                return (
                  <div key={step} className="flex items-center">
                    <div
                      className={`
                        w-3 h-3 rounded-full border-2 transition-all duration-300
                        ${isActive 
                          ? 'bg-orange-500 border-orange-500 scale-150 animate-pulse' 
                          : isCompleted 
                            ? 'bg-green-500 border-green-500' 
                            : 'bg-gray-300 border-gray-400'
                        }
                      `}
                    />
                    {index < 3 && (
                      <div
                        className={`
                          w-12 h-0.5 mx-1 transition-colors duration-300
                          ${isCompleted ? 'bg-green-500' : 'bg-gray-300'}
                        `}
                      />
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}
      
      {/* Header */}
      <header className="text-center py-8 px-4">
        <h1 className="text-5xl font-bold text-gray-800 mb-4">
          🍳 Recipe Quest
        </h1>
        <p className="text-xl text-gray-600 max-w-2xl mx-auto">
          Test your culinary creativity! Get random ingredients and let AI help you create, visualize, and rate your dish.
        </p>
      </header>

      <div className={`container mx-auto px-4 pb-8 ${
        (state.currentStep !== GameStep.Ready && state.currentStep !== GameStep.SelectIngredients) ? 'pt-24' : ''
      }`}>

        {/* Processing Status Card */}
        {state.isLoading && state.currentStep !== GameStep.SelectIngredients && (
          <div className="max-w-2xl mx-auto mb-8 p-6 bg-blue-50 border-2 border-blue-200 rounded-xl shadow-lg">
            <div className="text-center">
              <div className="flex items-center justify-center gap-3 mb-4">
                <div className="w-8 h-8 border-3 border-blue-400 border-t-transparent rounded-full animate-spin" />
                <div className="text-xl font-bold text-blue-800">Processing...</div>
              </div>
              
              <div className="space-y-2">
                {state.currentStep === GameStep.Recipe && (
                  <>
                    <p className="text-blue-700 font-medium">🤖 AI Chef is analyzing your ingredients</p>
                    <p className="text-sm text-blue-600">✨ Creating a custom recipe with: {state.selectedIngredients.join(', ')}</p>
                    <p className="text-xs text-blue-500 mt-3">📡 Receiving live updates from the kitchen...</p>
                  </>
                )}
                
                {state.currentStep === GameStep.Image && (
                  <>
                    <p className="text-blue-700 font-medium">🎨 Visualizing your dish</p>
                    <p className="text-sm text-blue-600">📸 Creating an appetizing image of your recipe</p>
                    <p className="text-xs text-blue-500 mt-3">🖼️ This may take a moment...</p>
                  </>
                )}
                
                {state.currentStep === GameStep.Evaluation && (
                  <>
                    <p className="text-blue-700 font-medium">⚖️ Professional chef evaluation</p>
                    <p className="text-sm text-blue-600">👨‍🍳 Scoring your creativity, technique, and flavor</p>
                    <p className="text-xs text-blue-500 mt-3">🏆 Preparing your final results...</p>
                  </>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Error State */}
        {state.error && (
          <div className="max-w-2xl mx-auto mb-8 p-4 bg-red-100 border-2 border-red-200 rounded-xl">
            <div className="text-center">
              <div className="text-2xl mb-2">😅</div>
              <p className="text-red-800 font-medium">Oops! Something went wrong</p>
              <p className="text-red-600 text-sm mt-1">{state.error}</p>
              <button
                onClick={actions.resetGame}
                className="mt-3 px-4 py-2 bg-red-500 text-white rounded-lg hover:bg-red-600 transition-colors"
              >
                Try Again
              </button>
            </div>
          </div>
        )}

        {/* Start Game Button */}
        {state.currentStep === GameStep.Ready && (
          <div className="text-center max-w-lg mx-auto">
            <div className="bg-white rounded-2xl shadow-xl p-8 border-4 border-orange-200">
              <div className="text-6xl mb-6">🎯</div>
              <h2 className="text-2xl font-bold text-gray-800 mb-4">
                Ready for the Challenge?
              </h2>
              <p className="text-gray-600 mb-8 leading-relaxed">
                Choose your 4 favorite ingredients and start your recipe quest! 
                The AI will help you create a recipe, visualize your dish, and give you a professional rating.
              </p>
              <button
                onClick={actions.startGame}
                disabled={state.isLoading}
                className="
                  bg-gradient-to-r from-orange-500 to-red-500 hover:from-orange-600 hover:to-red-600
                  disabled:from-gray-400 disabled:to-gray-500
                  text-white font-bold py-4 px-8 rounded-xl text-xl
                  transform transition-all duration-200 hover:scale-105 hover:shadow-lg
                  disabled:cursor-not-allowed disabled:transform-none
                "
              >
                {state.isLoading ? (
                  <span className="flex items-center gap-3">
                    <div className="w-6 h-6 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    Starting Challenge...
                  </span>
                ) : (
                  '🚀 Start Recipe Quest'
                )}
              </button>
            </div>
          </div>
        )}

        {/* Ingredient Selection */}
        {state.currentStep === GameStep.SelectIngredients && (
          <div className="max-w-6xl mx-auto">
            <div className="bg-white rounded-2xl shadow-xl p-8 mb-8">
              <div className="text-center mb-8">
                <div className="text-4xl mb-3">🛒</div>
                <h2 className="text-2xl font-bold text-gray-800 mb-2">
                  Choose Your Ingredients
                </h2>
                <p className="text-gray-600">
                  Select exactly 4 ingredients to create your recipe ({state.selectedIngredients.length}/4 selected)
                </p>
              </div>

              {/* Available Ingredients Grid */}
              <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-3 mb-8">
                {availableIngredients.map((ingredient) => {
                  const isSelected = state.selectedIngredients.includes(ingredient.name);
                  const canSelect = state.selectedIngredients.length < 4 || isSelected;
                  
                  return (
                    <button
                      key={ingredient.name}
                      onClick={() => 
                        isSelected 
                          ? actions.removeIngredient(ingredient.name)
                          : actions.addIngredient(ingredient.name)
                      }
                      disabled={!canSelect}
                      className={`
                        p-4 rounded-xl border-3 transition-all duration-200 text-center min-h-[80px]
                        ${isSelected 
                          ? 'bg-gradient-to-br from-orange-400 to-red-500 border-orange-600 text-white shadow-lg transform scale-105 font-bold' 
                          : canSelect
                            ? 'bg-white border-gray-300 hover:border-orange-400 hover:bg-orange-50 text-gray-800 shadow hover:shadow-md'
                            : 'bg-gray-50 border-gray-200 text-gray-400 cursor-not-allowed'
                        }
                        ${canSelect && !isSelected ? 'hover:scale-102' : ''}
                      `}
                    >
                      <div className="text-2xl mb-1">{ingredient.emoji}</div>
                      <div className="text-sm font-medium capitalize">
                        {ingredient.name}
                      </div>
                    </button>
                  );
                })}
              </div>

              {/* Selected Ingredients Display */}
              {state.selectedIngredients.length > 0 && (
                <div className="bg-gradient-to-r from-orange-100 to-red-100 rounded-2xl p-6 mb-6 border-2 border-orange-300 shadow-lg">
                  <h3 className="text-xl font-bold text-gray-800 mb-4 text-center flex items-center justify-center gap-2">
                    <span>🍽️</span>
                    Selected Ingredients
                    <span className="bg-orange-500 text-white text-sm px-2 py-1 rounded-full">
                      {state.selectedIngredients.length}/4
                    </span>
                  </h3>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                    {state.selectedIngredients.map((ingredient) => {
                      const ingredientData = availableIngredients.find(ing => ing.name === ingredient);
                      return (
                        <div
                          key={ingredient}
                          className="bg-white rounded-xl p-4 border-2 border-orange-300 shadow-md hover:shadow-lg transition-all duration-200"
                        >
                          <div className="text-center">
                            <div className="text-3xl mb-2">{ingredientData?.emoji}</div>
                            <div className="text-sm font-semibold text-gray-800 capitalize mb-2">
                              {ingredient}
                            </div>
                            <button
                              onClick={() => actions.removeIngredient(ingredient)}
                              className="bg-red-500 hover:bg-red-600 text-white text-xs px-3 py-1 rounded-full transition-colors duration-200"
                            >
                              Remove
                            </button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* Start Recipe Generation Button */}
              <div className="text-center">
                {state.selectedIngredients.length === 4 && (
                  <div className="mb-4 p-3 bg-green-50 border border-green-300 rounded-lg">
                    <div className="text-green-800 font-semibold text-sm">
                      ✨ Perfect! You&apos;ve selected 4 ingredients. Ready to create your masterpiece?
                    </div>
                  </div>
                )}
                
                <button
                  onClick={actions.startRecipeGeneration}
                  disabled={state.selectedIngredients.length < 1 || state.isLoading}
                  className="
                    bg-gradient-to-r from-green-500 to-blue-500 hover:from-green-600 hover:to-blue-600
                    disabled:from-gray-400 disabled:to-gray-500
                    text-white font-bold py-4 px-8 rounded-xl text-lg
                    transform transition-all duration-200 hover:scale-105 hover:shadow-lg
                    disabled:cursor-not-allowed disabled:transform-none
                    min-w-[280px]
                  "
                >
                  {state.isLoading ? (
                    <span className="flex items-center justify-center gap-3">
                      <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                      <div className="flex flex-col items-start text-sm">
                        <span>Creating Recipe...</span>
                        <span className="text-xs opacity-80">🤖 AI Chef is working...</span>
                      </div>
                    </span>
                  ) : (
                    <span className="flex items-center justify-center gap-2">
                      <span>🍳</span>
                      <span>Create Recipe</span>
                      {state.selectedIngredients.length > 0 && (
                        <span className="bg-white/20 px-2 py-1 rounded-full text-sm">
                          {state.selectedIngredients.length} ingredients
                        </span>
                      )}
                    </span>
                  )}
                </button>
                
                {state.selectedIngredients.length > 0 && state.selectedIngredients.length < 4 && (
                  <p className="mt-3 text-sm text-gray-600">
                    💡 Tip: Select {4 - state.selectedIngredients.length} more ingredient{4 - state.selectedIngredients.length > 1 ? 's' : ''} for the best recipe results!
                  </p>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Content Area - Shows different content based on game step */}
        <div className="space-y-8">

          {/* Recipe Display */}
          <RecipeDisplay
            recipe={state.recipe || ''}
            isVisible={state.currentStep === GameStep.Recipe || 
                      (!!state.recipe && state.currentStep !== GameStep.Ready && state.currentStep !== GameStep.Result)}
            isStreaming={state.currentStep === GameStep.Recipe && state.isLoading}
          />

          {/* Image Display */}
          <ImageDisplay
            imageUrl={state.imageUrl || ''}
            dishName={state.recipe?.split('\n')[0]?.replace(/Recipe name:\s*/i, '') || 'Your Dish'}
            isVisible={state.currentStep === GameStep.Image || 
                      (!!state.imageUrl && state.currentStep !== GameStep.Ready && state.currentStep !== GameStep.Result)}
            isGenerating={state.isGeneratingImage}
            generationProgress={state.imageGenerationProgress}
          />

          {/* Game Result */}
          {state.currentStep === GameStep.Result && state.score !== undefined && (
            <GameResult
              score={state.score}
              feedback={state.feedback || 'Great job on your Recipe Quest!'}
              ingredients={state.selectedIngredients}
              onPlayAgain={actions.resetGame}
            />
          )}
        </div>

        {/* Footer */}
        <footer className="text-center mt-16 text-gray-500">
          <p className="text-sm">
            Powered by Genkit + Next.js 15 | Embark on your Recipe Quest!
          </p>
        </footer>
      </div>
    </div>
  );
}
